version: "3.3"

services:
    mosquitto:
        image: eclipse-mosquitto
        container_name: mosquitto
        restart: unless-stopped
        ports:
            - "1883:1883"
        volumes:
            - ./mosquitto/config:/mosquitto/config